apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-ingress
  labels:
    app: prometheus
spec:
  hosts:
    - "prometheus.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 9090
            host: monitoring-prometheus.monitoring.svc.cluster.local
