apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: breezewiki-config
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: breezewiki-config
  data:
    - secretKey: config
      remoteRef:
        key: default/breezewiki-config
        property: config
