apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-config
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-config
  data:
    - secretKey: client-id
      remoteRef:
        key: istio/oauth2-proxy
        property: clientId
    - secretKey: client-secret
      remoteRef:
        key: istio/oauth2-proxy
        property: clientSecret
    - secretKey: cookie-secret
      remoteRef:
        key: istio/oauth2-proxy
        property: cookieSecret
