apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'grafana.adryan.me'
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: monitoring:/ConfigMap:monitoring/monitoring-grafana
  creationTimestamp: "2025-11-14T00:39:09Z"
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.2.1
    helm.sh/chart: grafana-10.1.4
  name: monitoring-grafana
  namespace: monitoring
  resourceVersion: "1716851"
  uid: 17e434cd-cb16-4a7b-8747-0868f1969bd0
