apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'grafana.adryan.me'
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability:/ConfigMap:observability/observability-grafana
  creationTimestamp: "2025-11-13T23:46:52Z"
  labels:
    app.kubernetes.io/instance: observability
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.2.1
    helm.sh/chart: grafana-10.1.4
  name: observability-grafana
  namespace: observability
  resourceVersion: "1700207"
  uid: 2baddaab-a661-4889-a3c3-f45808afc2c7
